// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlockMsg struct {
	Id                   int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Vhp                  []byte      `protobuf:"bytes,2,opt,name=vhp,proto3" json:"vhp,omitempty"`
	Vhb                  []byte      `protobuf:"bytes,3,opt,name=vhb,proto3" json:"vhb,omitempty"`
	Ked                  []byte      `protobuf:"bytes,4,opt,name=ked,proto3" json:"ked,omitempty"`
	Vnf                  int32       `protobuf:"varint,5,opt,name=vnf,proto3" json:"vnf,omitempty"`
	Ar                   int32       `protobuf:"varint,6,opt,name=ar,proto3" json:"ar,omitempty"`
	Shards               []*ShardMsg `protobuf:"bytes,7,rep,name=shards,proto3" json:"shards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BlockMsg) Reset()         { *m = BlockMsg{} }
func (m *BlockMsg) String() string { return proto.CompactTextString(m) }
func (*BlockMsg) ProtoMessage()    {}
func (*BlockMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *BlockMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockMsg.Unmarshal(m, b)
}
func (m *BlockMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockMsg.Marshal(b, m, deterministic)
}
func (m *BlockMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockMsg.Merge(m, src)
}
func (m *BlockMsg) XXX_Size() int {
	return xxx_messageInfo_BlockMsg.Size(m)
}
func (m *BlockMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockMsg.DiscardUnknown(m)
}

var xxx_messageInfo_BlockMsg proto.InternalMessageInfo

func (m *BlockMsg) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BlockMsg) GetVhp() []byte {
	if m != nil {
		return m.Vhp
	}
	return nil
}

func (m *BlockMsg) GetVhb() []byte {
	if m != nil {
		return m.Vhb
	}
	return nil
}

func (m *BlockMsg) GetKed() []byte {
	if m != nil {
		return m.Ked
	}
	return nil
}

func (m *BlockMsg) GetVnf() int32 {
	if m != nil {
		return m.Vnf
	}
	return 0
}

func (m *BlockMsg) GetAr() int32 {
	if m != nil {
		return m.Ar
	}
	return 0
}

func (m *BlockMsg) GetShards() []*ShardMsg {
	if m != nil {
		return m.Shards
	}
	return nil
}

type ShardMsg struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Vhf                  []byte   `protobuf:"bytes,2,opt,name=vhf,proto3" json:"vhf,omitempty"`
	Bindex               uint64   `protobuf:"varint,3,opt,name=bindex,proto3" json:"bindex,omitempty"`
	Offset               int32    `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	NodeID               int32    `protobuf:"varint,5,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	NodeID2              int32    `protobuf:"varint,6,opt,name=nodeID2,proto3" json:"nodeID2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardMsg) Reset()         { *m = ShardMsg{} }
func (m *ShardMsg) String() string { return proto.CompactTextString(m) }
func (*ShardMsg) ProtoMessage()    {}
func (*ShardMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *ShardMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardMsg.Unmarshal(m, b)
}
func (m *ShardMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardMsg.Marshal(b, m, deterministic)
}
func (m *ShardMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardMsg.Merge(m, src)
}
func (m *ShardMsg) XXX_Size() int {
	return xxx_messageInfo_ShardMsg.Size(m)
}
func (m *ShardMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ShardMsg proto.InternalMessageInfo

func (m *ShardMsg) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ShardMsg) GetVhf() []byte {
	if m != nil {
		return m.Vhf
	}
	return nil
}

func (m *ShardMsg) GetBindex() uint64 {
	if m != nil {
		return m.Bindex
	}
	return 0
}

func (m *ShardMsg) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ShardMsg) GetNodeID() int32 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *ShardMsg) GetNodeID2() int32 {
	if m != nil {
		return m.NodeID2
	}
	return 0
}

type ShardMetaMsg struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Bindex               uint64   `protobuf:"varint,2,opt,name=bindex,proto3" json:"bindex,omitempty"`
	Offset               int32    `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Vnf                  int32    `protobuf:"varint,4,opt,name=vnf,proto3" json:"vnf,omitempty"`
	Ar                   int32    `protobuf:"varint,5,opt,name=ar,proto3" json:"ar,omitempty"`
	Timestamp            int64    `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardMetaMsg) Reset()         { *m = ShardMetaMsg{} }
func (m *ShardMetaMsg) String() string { return proto.CompactTextString(m) }
func (*ShardMetaMsg) ProtoMessage()    {}
func (*ShardMetaMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *ShardMetaMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardMetaMsg.Unmarshal(m, b)
}
func (m *ShardMetaMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardMetaMsg.Marshal(b, m, deterministic)
}
func (m *ShardMetaMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardMetaMsg.Merge(m, src)
}
func (m *ShardMetaMsg) XXX_Size() int {
	return xxx_messageInfo_ShardMetaMsg.Size(m)
}
func (m *ShardMetaMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardMetaMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ShardMetaMsg proto.InternalMessageInfo

func (m *ShardMetaMsg) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ShardMetaMsg) GetBindex() uint64 {
	if m != nil {
		return m.Bindex
	}
	return 0
}

func (m *ShardMetaMsg) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ShardMetaMsg) GetVnf() int32 {
	if m != nil {
		return m.Vnf
	}
	return 0
}

func (m *ShardMetaMsg) GetAr() int32 {
	if m != nil {
		return m.Ar
	}
	return 0
}

func (m *ShardMetaMsg) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type CheckPointMsg struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Start                int64    `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckPointMsg) Reset()         { *m = CheckPointMsg{} }
func (m *CheckPointMsg) String() string { return proto.CompactTextString(m) }
func (*CheckPointMsg) ProtoMessage()    {}
func (*CheckPointMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

func (m *CheckPointMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPointMsg.Unmarshal(m, b)
}
func (m *CheckPointMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPointMsg.Marshal(b, m, deterministic)
}
func (m *CheckPointMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPointMsg.Merge(m, src)
}
func (m *CheckPointMsg) XXX_Size() int {
	return xxx_messageInfo_CheckPointMsg.Size(m)
}
func (m *CheckPointMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPointMsg.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPointMsg proto.InternalMessageInfo

func (m *CheckPointMsg) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CheckPointMsg) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *CheckPointMsg) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*BlockMsg)(nil), "pb.BlockMsg")
	proto.RegisterType((*ShardMsg)(nil), "pb.ShardMsg")
	proto.RegisterType((*ShardMetaMsg)(nil), "pb.ShardMetaMsg")
	proto.RegisterType((*CheckPointMsg)(nil), "pb.CheckPointMsg")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0xd2, 0xcf, 0x4a, 0x2b, 0x31,
	0x14, 0x06, 0x70, 0x92, 0x34, 0xd3, 0xde, 0xb4, 0x57, 0x24, 0x88, 0x64, 0xe1, 0x62, 0x28, 0x2e,
	0x66, 0xd5, 0x45, 0x7d, 0x83, 0xea, 0x42, 0x17, 0x05, 0x49, 0x9f, 0x20, 0x69, 0x32, 0xed, 0x30,
	0x76, 0x12, 0x26, 0x41, 0xf4, 0x25, 0x5c, 0xfb, 0xb8, 0x92, 0x3f, 0xb5, 0x4c, 0xa9, 0xbb, 0xf3,
	0x7d, 0xc3, 0x1c, 0x7e, 0x1c, 0x42, 0xa6, 0xfe, 0xd3, 0x6a, 0xb7, 0xb0, 0xbd, 0xf1, 0x86, 0x42,
	0x2b, 0xe7, 0xdf, 0x80, 0x4c, 0x56, 0x6f, 0x66, 0xdb, 0xae, 0xdd, 0x8e, 0x5e, 0x11, 0xd8, 0x28,
	0x06, 0x4a, 0x50, 0x21, 0x0e, 0x1b, 0x45, 0xaf, 0x09, 0x7a, 0xdf, 0x5b, 0x06, 0x4b, 0x50, 0xcd,
	0x78, 0x18, 0x53, 0x23, 0x19, 0x3a, 0x36, 0x32, 0x34, 0xad, 0x56, 0x6c, 0x94, 0x9a, 0x56, 0xa7,
	0xbf, 0xba, 0x9a, 0xe1, 0x12, 0x54, 0x98, 0x87, 0x31, 0xec, 0x15, 0x3d, 0x2b, 0x62, 0x01, 0x45,
	0x4f, 0xef, 0x49, 0xe1, 0xf6, 0xa2, 0x57, 0x8e, 0x8d, 0x4b, 0x54, 0x4d, 0x97, 0xb3, 0x85, 0x95,
	0x8b, 0x4d, 0x68, 0xd6, 0x6e, 0xc7, 0xf3, 0xb7, 0xf9, 0x17, 0x20, 0x93, 0x63, 0x79, 0x99, 0x56,
	0x9f, 0x68, 0x35, 0xbd, 0x25, 0x85, 0x6c, 0x3a, 0xa5, 0x3f, 0xa2, 0x6e, 0xc4, 0x73, 0x0a, 0xbd,
	0xa9, 0x6b, 0xa7, 0x7d, 0x34, 0x62, 0x9e, 0x53, 0xe8, 0x3b, 0xa3, 0xf4, 0xcb, 0x53, 0x96, 0xe6,
	0x44, 0x19, 0x19, 0xa7, 0x69, 0x99, 0xc5, 0xc7, 0x18, 0x40, 0xb3, 0x04, 0xd2, 0x5e, 0x5c, 0x42,
	0x9d, 0x08, 0xf0, 0x0f, 0x02, 0x1a, 0x10, 0xf2, 0xa5, 0x46, 0xe7, 0x97, 0xc2, 0xbf, 0x97, 0xba,
	0x23, 0xff, 0x7c, 0x73, 0xd0, 0xce, 0x8b, 0x83, 0x8d, 0x1c, 0xc4, 0x4f, 0xc5, 0x7c, 0x43, 0xfe,
	0x3f, 0xee, 0xf5, 0xb6, 0x7d, 0x35, 0x4d, 0xe7, 0x87, 0x20, 0x1c, 0x41, 0x37, 0x04, 0x3b, 0x2f,
	0x7a, 0x1f, 0x3d, 0x88, 0xa7, 0x30, 0x5c, 0x8a, 0xce, 0x96, 0xae, 0xe0, 0x33, 0x90, 0x45, 0x7c,
	0x20, 0x0f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x78, 0x4d, 0x0c, 0x2f, 0x02, 0x00, 0x00,
}
